/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mml.ui.internal.MmlActivator;

public class MmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MmlActivator.getInstance().getInjector("org.xtext.example.mydsl.Mml");
	}

}
