/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MmlRuntimeModule;
import org.xtext.example.mydsl.MmlStandaloneSetup;
import org.xtext.example.mydsl.ide.MmlIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MmlIdeSetup extends MmlStandaloneSetup {
  @Override
  public Injector createInjector() {
    MmlRuntimeModule _mmlRuntimeModule = new MmlRuntimeModule();
    MmlIdeModule _mmlIdeModule = new MmlIdeModule();
    return Guice.createInjector(Modules2.mixin(_mmlRuntimeModule, _mmlIdeModule));
  }
}
