/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.mml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logistic Regression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.mml.MmlPackage#getLogisticRegression()
 * @model
 * @generated
 */
public interface LogisticRegression extends MLAlgorithm
{
} // LogisticRegression
