/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.mml;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>SVM Classification</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.mml.MmlPackage#getSVMClassification()
 * @model
 * @generated
 */
public enum SVMClassification implements Enumerator
{
  /**
   * The '<em><b>CClass</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CCLASS_VALUE
   * @generated
   * @ordered
   */
  CCLASS(0, "cClass", "C-classification"),

  /**
   * The '<em><b>Nu Class</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NU_CLASS_VALUE
   * @generated
   * @ordered
   */
  NU_CLASS(1, "nuClass", "nu-classification"),

  /**
   * The '<em><b>One Class</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ONE_CLASS_VALUE
   * @generated
   * @ordered
   */
  ONE_CLASS(2, "oneClass", "one-classification");

  /**
   * The '<em><b>CClass</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CCLASS
   * @model name="cClass" literal="C-classification"
   * @generated
   * @ordered
   */
  public static final int CCLASS_VALUE = 0;

  /**
   * The '<em><b>Nu Class</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NU_CLASS
   * @model name="nuClass" literal="nu-classification"
   * @generated
   * @ordered
   */
  public static final int NU_CLASS_VALUE = 1;

  /**
   * The '<em><b>One Class</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ONE_CLASS
   * @model name="oneClass" literal="one-classification"
   * @generated
   * @ordered
   */
  public static final int ONE_CLASS_VALUE = 2;

  /**
   * An array of all the '<em><b>SVM Classification</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final SVMClassification[] VALUES_ARRAY =
    new SVMClassification[]
    {
      CCLASS,
      NU_CLASS,
      ONE_CLASS,
    };

  /**
   * A public read-only list of all the '<em><b>SVM Classification</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<SVMClassification> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>SVM Classification</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SVMClassification get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SVMClassification result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SVM Classification</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SVMClassification getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SVMClassification result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>SVM Classification</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SVMClassification get(int value)
  {
    switch (value)
    {
      case CCLASS_VALUE: return CCLASS;
      case NU_CLASS_VALUE: return NU_CLASS;
      case ONE_CLASS_VALUE: return ONE_CLASS;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private SVMClassification(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //SVMClassification
