/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.mydsl.MmlRuntimeModule
import org.xtext.example.mydsl.MmlStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MmlIdeSetup extends MmlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MmlRuntimeModule, new MmlIdeModule))
	}
	
}
