/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.mml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mml.DT#getMax_depth <em>Max depth</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mml.MmlPackage#getDT()
 * @model
 * @generated
 */
public interface DT extends MLAlgorithm
{
  /**
   * Returns the value of the '<em><b>Max depth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max depth</em>' attribute.
   * @see #setMax_depth(int)
   * @see org.xtext.example.mydsl.mml.MmlPackage#getDT_Max_depth()
   * @model
   * @generated
   */
  int getMax_depth();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mml.DT#getMax_depth <em>Max depth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max depth</em>' attribute.
   * @see #getMax_depth()
   * @generated
   */
  void setMax_depth(int value);

} // DT
