/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.mml;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Validation Metric</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.mml.MmlPackage#getValidationMetric()
 * @model
 * @generated
 */
public enum ValidationMetric implements Enumerator
{
  /**
   * The '<em><b>BALANCED ACCURACY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BALANCED_ACCURACY_VALUE
   * @generated
   * @ordered
   */
  BALANCED_ACCURACY(0, "BALANCED_ACCURACY", "balanced_accuracy"),

  /**
   * The '<em><b>RECALL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RECALL_VALUE
   * @generated
   * @ordered
   */
  RECALL(1, "RECALL", "recall"),

  /**
   * The '<em><b>PRECISION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRECISION_VALUE
   * @generated
   * @ordered
   */
  PRECISION(2, "PRECISION", "precision"),

  /**
   * The '<em><b>F1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #F1_VALUE
   * @generated
   * @ordered
   */
  F1(3, "F1", "F1"),

  /**
   * The '<em><b>ACCURACY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCURACY_VALUE
   * @generated
   * @ordered
   */
  ACCURACY(4, "ACCURACY", "accuracy"),

  /**
   * The '<em><b>MACRO RECALL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MACRO_RECALL_VALUE
   * @generated
   * @ordered
   */
  MACRO_RECALL(5, "MACRO_RECALL", "macro_recall"),

  /**
   * The '<em><b>MACRO PRECISION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MACRO_PRECISION_VALUE
   * @generated
   * @ordered
   */
  MACRO_PRECISION(6, "MACRO_PRECISION", "macro_precision"),

  /**
   * The '<em><b>MACRO F1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MACRO_F1_VALUE
   * @generated
   * @ordered
   */
  MACRO_F1(7, "MACRO_F1", "macro_F1"),

  /**
   * The '<em><b>MACRO ACCURACY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MACRO_ACCURACY_VALUE
   * @generated
   * @ordered
   */
  MACRO_ACCURACY(8, "MACRO_ACCURACY", "macro_accuracy");

  /**
   * The '<em><b>BALANCED ACCURACY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BALANCED_ACCURACY
   * @model literal="balanced_accuracy"
   * @generated
   * @ordered
   */
  public static final int BALANCED_ACCURACY_VALUE = 0;

  /**
   * The '<em><b>RECALL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RECALL
   * @model literal="recall"
   * @generated
   * @ordered
   */
  public static final int RECALL_VALUE = 1;

  /**
   * The '<em><b>PRECISION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRECISION
   * @model literal="precision"
   * @generated
   * @ordered
   */
  public static final int PRECISION_VALUE = 2;

  /**
   * The '<em><b>F1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #F1
   * @model
   * @generated
   * @ordered
   */
  public static final int F1_VALUE = 3;

  /**
   * The '<em><b>ACCURACY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCURACY
   * @model literal="accuracy"
   * @generated
   * @ordered
   */
  public static final int ACCURACY_VALUE = 4;

  /**
   * The '<em><b>MACRO RECALL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MACRO_RECALL
   * @model literal="macro_recall"
   * @generated
   * @ordered
   */
  public static final int MACRO_RECALL_VALUE = 5;

  /**
   * The '<em><b>MACRO PRECISION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MACRO_PRECISION
   * @model literal="macro_precision"
   * @generated
   * @ordered
   */
  public static final int MACRO_PRECISION_VALUE = 6;

  /**
   * The '<em><b>MACRO F1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MACRO_F1
   * @model literal="macro_F1"
   * @generated
   * @ordered
   */
  public static final int MACRO_F1_VALUE = 7;

  /**
   * The '<em><b>MACRO ACCURACY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MACRO_ACCURACY
   * @model literal="macro_accuracy"
   * @generated
   * @ordered
   */
  public static final int MACRO_ACCURACY_VALUE = 8;

  /**
   * An array of all the '<em><b>Validation Metric</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ValidationMetric[] VALUES_ARRAY =
    new ValidationMetric[]
    {
      BALANCED_ACCURACY,
      RECALL,
      PRECISION,
      F1,
      ACCURACY,
      MACRO_RECALL,
      MACRO_PRECISION,
      MACRO_F1,
      MACRO_ACCURACY,
    };

  /**
   * A public read-only list of all the '<em><b>Validation Metric</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ValidationMetric> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Validation Metric</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ValidationMetric get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ValidationMetric result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Validation Metric</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ValidationMetric getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ValidationMetric result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Validation Metric</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ValidationMetric get(int value)
  {
    switch (value)
    {
      case BALANCED_ACCURACY_VALUE: return BALANCED_ACCURACY;
      case RECALL_VALUE: return RECALL;
      case PRECISION_VALUE: return PRECISION;
      case F1_VALUE: return F1;
      case ACCURACY_VALUE: return ACCURACY;
      case MACRO_RECALL_VALUE: return MACRO_RECALL;
      case MACRO_PRECISION_VALUE: return MACRO_PRECISION;
      case MACRO_F1_VALUE: return MACRO_F1;
      case MACRO_ACCURACY_VALUE: return MACRO_ACCURACY;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ValidationMetric(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ValidationMetric
