/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.mml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XFormula</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.mml.MmlPackage#getXFormula()
 * @model
 * @generated
 */
public interface XFormula extends EObject
{
} // XFormula
