/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.mml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XGboost</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.mml.MmlPackage#getXGboost()
 * @model
 * @generated
 */
public interface XGboost extends MLAlgorithm
{
} // XGboost
