/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.mml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.mml.LogisticRegression;
import org.xtext.example.mydsl.mml.MmlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Logistic Regression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LogisticRegressionImpl extends MLAlgorithmImpl implements LogisticRegression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LogisticRegressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MmlPackage.Literals.LOGISTIC_REGRESSION;
  }

} //LogisticRegressionImpl
