/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.mml.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.mml.MmlPackage;
import org.xtext.example.mydsl.mml.XFormula;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XFormula</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XFormulaImpl extends MinimalEObjectImpl.Container implements XFormula
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XFormulaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MmlPackage.Literals.XFORMULA;
  }

} //XFormulaImpl
