/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.mydsl.mml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.mml.MmlPackage;
import org.xtext.example.mydsl.mml.XGboost;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XGboost</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XGboostImpl extends MLAlgorithmImpl implements XGboost
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XGboostImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MmlPackage.Literals.XGBOOST;
  }

} //XGboostImpl
