@startuml MMLClassDiagram

abstract class Script {
    String scriptName
    String authorName
}
abstract class Bloc {
    String name
}


class Data {
    String filepath
    bool header
    String[] qualiVariables
    String[] intVariables
    String[] labels
    float testSize
}

abstract class Algo {
    {static} String id
    void display()
}

class Compare {
    Algo[] listAlgos
    String[] metrics
}

class RandomForest {

}

class KNN {
    int k
    String[] distance
}

Data -[hidden] Algo
Algo -[hidden] Compare

Compare *-- Algo : have 2..* >

Script <|-- Bloc
Bloc <|-- Data
Bloc <|-- Algo
Bloc <|-- Compare 
Algo <|.. RandomForest
Algo <|.. KNN

@enduml
